version: '3'

services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: fragments
      POSTGRES_PASSWORD: fragments
      POSTGRES_DB: fragmentsclean
    ports:
      - "5441:5432"
    volumes:
      - ./docker-postgresql-data-for-dev:/var/lib/postgresql/data
      - ./src/main/resources/fragments-ddl.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: local-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: local-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # Ce que verront tes clients Spring (ta machine = localhost:9092)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Pratique en dev : cr√©e les topics automatiquement si besoin
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
