version: '3'

services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: fragments
      POSTGRES_PASSWORD: fragments
      POSTGRES_DB: fragmentsclean
    ports:
      - 5441:5432
    volumes:
      - ./docker-postgresql-data-for-dev:/var/lib/postgresql/data
      - ./src/main/resources/fragments-ddl.sql:/docker-entrypoint-initdb.d/init.sql